
CREATE TABLE CMT_ALERT(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR2(255),
    ALERT_TYPE_ID BIGINT NOT NULL,
    NOTIF_METH_TYPE_ID BIGINT NOT NULL,
    STATUS BIGINT NOT NULL,
    CREATE_ON TIMESTAMP NOT NULL,
    FOREIGN KEY (ALERT_TYPE_ID) REFERENCES CMT_COMMON_LOV(ID),
    FOREIGN KEY (NOTIF_METH_TYPE_ID) REFERENCES CMT_COMMON_LOV(ID),
    FOREIGN KEY (STATUS) REFERENCES CMT_COMMON_LOV(ID)
);

CREATE TABLE CMT_ALERT_PARAMS(
    NAME VARCHAR2(255) NOT NULL,
    VALUE VARCHAR2(500) NOT NULL,
    ALERT_ID BIGINT NOT NULL
);
