INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (1, 'ACTIVE', 'Active', 'STATUS' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (2, 'IN-ACTIVE', 'In-active', 'STATUS' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (3, 'VEHICLE_ROUTE', 'Vehicle Route', 'ROUTE_TYPE' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (4, 'SHIPMENT_ROUTE', 'Shipment Route', 'ROUTE_TYPE' );


INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (5, 'DEVIATION_ALERT', 'Deviation Alert', 'ALERT_TYPE' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (6, 'EMAIL', 'email', 'ALERT_NOTIF_METH_TYPE' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (7, 'WEB_PUSH', 'Web Push', 'ALERT_NOTIF_METH_TYPE' );


INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (8, 'NEW', 'New', 'ALERT_STATUS' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (9, 'SENT', 'Sent', 'ALERT_STATUS' );
INSERT INTO CMT_COMMON_LOV (ID, NAME, VALUE, TYPE) VALUES (10, 'FAILED', 'Failed', 'ALERT_STATUS' );